# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Todolist' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SwiftGen'
  pod 'MagicalRecord', :git => 'https://github.com/hardikdevios/MagicalRecord.git', :tag => '2.3.11'

  target 'TodolistTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TodolistUITests' do
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
      config.build_settings['CODE_SIGN_IDENTITY'] = ""
    end
  end
end

